//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string UserNo { get; set; }
        public string UserRealName { get; set; }
        public Nullable<System.DateTime> UserBirthDay { get; set; }
        public string UserGender { get; set; }
        public string UserIdno { get; set; }
        public string UserAreaCode { get; set; }
        public string UserMailingAddress { get; set; }
        public string UserHouseholdAddress { get; set; }
        public string UserHomePhone { get; set; }
        public string UserMobilePhone { get; set; }
        public Nullable<System.DateTime> UserOnBoardDay { get; set; }
        public Nullable<System.DateTime> UserResignationDay { get; set; }
        public string UserBelongCompany { get; set; }
        public string UserWorkPlace { get; set; }
        public string UserDept { get; set; }
        public string UserBelongDept { get; set; }
        public string UserJobCategory { get; set; }
        public string UserProIdentity { get; set; }
        public string UserPhoto { get; set; }
        public string UserRTPushAccount { get; set; }
        public Nullable<System.DateTime> UserCreateDate { get; set; }
    }
}
