//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class body_measure
    {
        public string id { get; set; }
        public Nullable<int> intServerID { get; set; }
        public string strUserAccount { get; set; }
        public Nullable<System.DateTime> datRecordTime { get; set; }
        public Nullable<int> intTypeID { get; set; }
        public Nullable<int> intSystolic { get; set; }
        public Nullable<int> intDiastolic { get; set; }
        public Nullable<int> intPulse { get; set; }
        public Nullable<int> intConsistencyBefore { get; set; }
        public Nullable<int> intConsistencyAfter { get; set; }
        public Nullable<decimal> floWeight { get; set; }
        public Nullable<decimal> floBodyFat { get; set; }
        public Nullable<decimal> floBodyFatWeight { get; set; }
        public Nullable<decimal> floBmi { get; set; }
        public Nullable<decimal> floBmr { get; set; }
        public Nullable<decimal> floWaistline { get; set; }
        public Nullable<decimal> floButtocks { get; set; }
        public Nullable<decimal> floRateOfBone { get; set; }
        public Nullable<decimal> floSoftLeanMass { get; set; }
        public Nullable<decimal> floTotalBodyWater { get; set; }
        public Nullable<decimal> floAn { get; set; }
        public Nullable<decimal> floFl { get; set; }
        public Nullable<decimal> floSf { get; set; }
        public Nullable<decimal> floVf { get; set; }
        public Nullable<decimal> floHeight { get; set; }
        public Nullable<decimal> floTemp { get; set; }
        public Nullable<decimal> floFfm { get; set; }
        public Nullable<decimal> floTbw { get; set; }
        public Nullable<decimal> floNeck { get; set; }
        public Nullable<decimal> floWrist { get; set; }
        public string strMemo { get; set; }
        public string strSelf { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<decimal> S3 { get; set; }
        public Nullable<decimal> S4 { get; set; }
        public Nullable<decimal> EMAT { get; set; }
        public Nullable<decimal> SDI { get; set; }
        public Nullable<decimal> floForeheadTemp { get; set; }
        public Nullable<decimal> floEarTemp { get; set; }
        public Nullable<decimal> floUricAcid { get; set; }
        public Nullable<decimal> floCholesterol { get; set; }
        public Nullable<int> intUnit { get; set; }
        public string floFundus { get; set; }
        public string floNeurology { get; set; }
        public string floBoneDensity { get; set; }
        public string strClo { get; set; }
        public string strC13 { get; set; }
        public string strHpSa { get; set; }
        public string strFobt { get; set; }
        public string strTf { get; set; }
        public string strHbvDna { get; set; }
        public string strHcvRna { get; set; }
        public string strHcvGen { get; set; }
        public string strHcvRav { get; set; }
        public string strARna { get; set; }
        public string strBRna { get; set; }
        public string strHba1c { get; set; }
        public string strEAG { get; set; }
        public string strChol { get; set; }
        public string strTG { get; set; }
        public string strHDL { get; set; }
        public string strLDL { get; set; }
        public string strNonHDL { get; set; }
        public string strCHOLHDL { get; set; }
        public string strTGHDL { get; set; }
        public string strAI { get; set; }
        public string strMicAlb { get; set; }
        public Nullable<decimal> floHead { get; set; }
        public string strHospitalAccount { get; set; }
        public string strUserName { get; set; }
        public string strUserTel { get; set; }
        public Nullable<System.DateTime> datUserBirthday { get; set; }
        public string strShake { get; set; }
        public string strNylon { get; set; }
        public string strFoot { get; set; }
        public Nullable<decimal> floInsulin { get; set; }
        public Nullable<decimal> floBs { get; set; }
        public Nullable<decimal> floLeftHandMass { get; set; }
        public Nullable<decimal> floRightHandMass { get; set; }
        public Nullable<decimal> floLeftFootMass { get; set; }
        public Nullable<decimal> floRightFootMass { get; set; }
        public Nullable<decimal> floBodyMass { get; set; }
        public Nullable<decimal> floSoftness { get; set; }
        public Nullable<decimal> floMassEndurance { get; set; }
        public Nullable<decimal> floHeartEndurance { get; set; }
        public Nullable<decimal> floInsulin2 { get; set; }
        public Nullable<decimal> floInsulin3 { get; set; }
        public Nullable<decimal> floInsulin4 { get; set; }
        public Nullable<decimal> floInsulinTimes { get; set; }
        public Nullable<decimal> floLeftHandFat { get; set; }
        public Nullable<decimal> floRightHandFat { get; set; }
        public Nullable<decimal> floLeftFootFat { get; set; }
        public Nullable<decimal> floRightFootFat { get; set; }
        public Nullable<decimal> floMainBodyFat { get; set; }
        public string strSource { get; set; }
        public Nullable<decimal> floSMI { get; set; }
        public Nullable<decimal> floGrip { get; set; }
        public Nullable<decimal> floWalk { get; set; }
        public Nullable<decimal> floPef { get; set; }
    }
}
