//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLisSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboDetail
    {
        public string CBDRowid { get; set; }
        public string CBMRowid { get; set; }
        public string CBDCode { get; set; }
        public string CBDDescription { get; set; }
        public Nullable<bool> CBDDisplayFlag { get; set; }
        public Nullable<int> CBDDisplayOrder { get; set; }
        public Nullable<System.DateTime> CBDLastModifiedDateTime { get; set; }
        public string CBDModifiedUserRowid { get; set; }
    }
}
