//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLisSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboMaster
    {
        public string CBMRowid { get; set; }
        public string CBMClass { get; set; }
        public string CBMDescription { get; set; }
        public string CBMRemark { get; set; }
        public string CBMGroup { get; set; }
        public Nullable<System.DateTime> CBMLastModifiedDateTime { get; set; }
        public string CBMModifiedUserRowid { get; set; }
    }
}
