//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratory_item
    {
        public string id { get; set; }
        public string laboratoryClass_id { get; set; }
        public string code { get; set; }
        public string nick { get; set; }
        public string name { get; set; }
        public string chnName { get; set; }
        public string unit { get; set; }
        public string standard { get; set; }
        public string nhi_code { get; set; }
        public string laboratory_clinic_code { get; set; }
    }
}
