//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lisLaboratorySchedule
    {
        public string LLSRowid { get; set; }
        public string HospRowid { get; set; }
        public string CBDRowid { get; set; }
        public string LLSTcpIp { get; set; }
        public string LLSLogin01 { get; set; }
        public string LLSLogin02 { get; set; }
        public string LLSLogin03 { get; set; }
        public string LLSPassword { get; set; }
        public string LLSAPIUrl { get; set; }
        public Nullable<bool> LLSMon { get; set; }
        public Nullable<bool> LLSTue { get; set; }
        public Nullable<bool> LLSWed { get; set; }
        public Nullable<bool> LLSThu { get; set; }
        public Nullable<bool> LLSFri { get; set; }
        public Nullable<bool> LLSSat { get; set; }
        public Nullable<bool> LLSSun { get; set; }
        public Nullable<System.DateTime> LLSTime01 { get; set; }
        public Nullable<System.DateTime> LLSTime02 { get; set; }
        public Nullable<System.DateTime> LLSTime03 { get; set; }
        public Nullable<System.DateTime> LLSTime04 { get; set; }
        public Nullable<System.DateTime> LLSTime05 { get; set; }
        public string LLSDescription { get; set; }
        public string LLSReceiveMail { get; set; }
    }
}
