//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLisSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisLaboratory_item
    {
        public string id { get; set; }
        public string LLRowid { get; set; }
        public string w_no { get; set; }
        public string h_no { get; set; }
        public string p_id { get; set; }
        public string c_id { get; set; }
        public string name { get; set; }
        public string birth { get; set; }
        public string sex { get; set; }
        public string c_date { get; set; }
        public string s_date { get; set; }
        public string m_date { get; set; }
        public string m_time { get; set; }
        public string item { get; set; }
        public string item_cname { get; set; }
        public string item_ename { get; set; }
        public string nhi_code { get; set; }
        public string CHD_V { get; set; }
        public string c_type { get; set; }
        public string low { get; set; }
        public string high { get; set; }
        public string meno { get; set; }
    }
}
