//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLisSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisLaboratory_str
    {
        public string Rowid { get; set; }
        public string LLRowid { get; set; }
        public string Field_name { get; set; }
        public string Field_type { get; set; }
        public string Field_length { get; set; }
        public string Field_HB { get; set; }
    }
}
