//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lisLaboratoryQueue
    {
        public string LQRowid { get; set; }
        public string SCHRowid { get; set; }
        public string LQDescription { get; set; }
        public System.DateTime LQDateTime { get; set; }
        public System.DateTime LQActiveDateTime { get; set; }
        public Nullable<System.DateTime> LQFinishDateTime { get; set; }
        public string LQResult { get; set; }
        public string LQMessage { get; set; }
        public Nullable<int> LQSeqno { get; set; }
        public string LQJobFilename { get; set; }
    }
}
