//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lisLaboratoryDetail
    {
        public string LLDRowid { get; set; }
        public string LLMRowid { get; set; }
        public string LLDCode { get; set; }
        public string LLDFieldName { get; set; }
        public string LLDFieldType { get; set; }
        public Nullable<int> LLDFieldLength { get; set; }
        public Nullable<int> LLDFieldFloatLength { get; set; }
        public string LLDFieldKind { get; set; }
        public string LLDFieldMemo { get; set; }
        public Nullable<int> LLDTextStartPos { get; set; }
        public Nullable<int> LLDTextEndPos { get; set; }
        public Nullable<int> LLDSeqno { get; set; }
        public string LLDMappingField { get; set; }
    }
}
