//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lisPatientLaboratoryMaster
    {
        public string PLMRowid { get; set; }
        public string PTRowid { get; set; }
        public string PLMPTIdno { get; set; }
        public string PLMPTName { get; set; }
        public string PLMPTBirthday { get; set; }
        public string PLMPTGender { get; set; }
        public string PLMPTCode { get; set; }
        public Nullable<System.DateTime> PLMClinicDate { get; set; }
        public Nullable<System.DateTime> PLMApplyDate { get; set; }
        public string PLMApplyTime { get; set; }
        public Nullable<System.DateTime> PLMInspDate { get; set; }
        public string PLMInspTime { get; set; }
        public Nullable<System.DateTime> PLMReportDate { get; set; }
        public string PLMReportTime { get; set; }
        public string PLMSNo { get; set; }
        public string PLMReqno { get; set; }
        public Nullable<System.DateTime> PLMInsertDate { get; set; }
    }
}
