//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLisSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISSchedule
    {
        public string SCHRowid { get; set; }
        public string HGRowid { get; set; }
        public Nullable<bool> SCHMon { get; set; }
        public Nullable<bool> SCHTue { get; set; }
        public Nullable<bool> SCHWed { get; set; }
        public Nullable<bool> SCHThu { get; set; }
        public Nullable<bool> SCHFri { get; set; }
        public Nullable<bool> SCHSat { get; set; }
        public Nullable<bool> SCHSun { get; set; }
        public Nullable<System.DateTime> SCHTime01 { get; set; }
        public Nullable<System.DateTime> SCHTime02 { get; set; }
        public Nullable<System.DateTime> SCHTime03 { get; set; }
        public Nullable<System.DateTime> SCHTime04 { get; set; }
        public Nullable<System.DateTime> SCHTime05 { get; set; }
        public string SCHDescription { get; set; }
        public string SCHReceiveMail { get; set; }
    }
}
