//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string id { get; set; }
        public string strPrgID { get; set; }
        public string strPrgPws { get; set; }
        public string strUserAccount { get; set; }
        public string strDisplayName { get; set; }
        public Nullable<bool> bolisMale { get; set; }
        public Nullable<bool> bolisAgreement { get; set; }
        public string strCell { get; set; }
        public string strEMail { get; set; }
        public string strPassword { get; set; }
        public string strTempPhoto { get; set; }
        public Nullable<System.DateTime> datBirthday { get; set; }
        public string strAddSecCode { get; set; }
        public string strCommunityCode { get; set; }
        public Nullable<int> intUserID { get; set; }
        public Nullable<decimal> floHeight { get; set; }
        public Nullable<decimal> floWeight { get; set; }
        public string ftp_file_id { get; set; }
        public Nullable<int> intRsRecno { get; set; }
        public string strRecno { get; set; }
        public string strName { get; set; }
        public string strShortcut { get; set; }
        public string strIdno { get; set; }
        public string strTel { get; set; }
        public string strAddr { get; set; }
        public string strCompanyName { get; set; }
        public string strCompanyTel { get; set; }
        public string strCompanyTitle { get; set; }
        public string strGroup { get; set; }
        public string strBlood { get; set; }
        public Nullable<int> intMerry { get; set; }
        public Nullable<int> intWork { get; set; }
        public string strHabit { get; set; }
        public string strAllergy { get; set; }
        public string strHistory { get; set; }
        public string strDrug { get; set; }
        public string strWorkOther { get; set; }
        public string strAllergyOther { get; set; }
        public string strHistoryOther { get; set; }
        public string strDrugOther { get; set; }
        public string hisMemo { get; set; }
        public string phsTypeMemo { get; set; }
        public string laboratoryMemo { get; set; }
        public string patientMemo { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<bool> isFreezen { get; set; }
        public string hospital_no { get; set; }
        public string employee_id { get; set; }
        public string doctor_id { get; set; }
        public string doctorG8_id { get; set; }
        public string g8_mode { get; set; }
    }
}
