//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMLISSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysHospitalParam
    {
        public string HospRowid { get; set; }
        public bool HospLisToChiefComplaint { get; set; }
        public bool HospLisOutliers { get; set; }
        public string HospLisDateStyle { get; set; }
        public string HospLisDateFormat { get; set; }
        public bool HospLisItemTemp01 { get; set; }
        public bool HospLisItemTemp02 { get; set; }
        public bool HospLisItemTemp03 { get; set; }
        public bool HospLisItemTemp04 { get; set; }
        public string HospLisItemAndValueTemplate { get; set; }
        public string HospLisDelimiter { get; set; }
        public string HospLisEndingSymbol { get; set; }
        public int HospLisRowCount { get; set; }
        public int HospLisColumnSpace { get; set; }
        public int HospLisPushDay { get; set; }
    }
}
